---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldilocks-web
  labels:
    app.kubernetes.io/name: goldilocks
    app.kubernetes.io/component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: goldilocks
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goldilocks
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: goldilocks-web
      containers:
        - name: goldilocks
          image: "quay.io/fairwinds/goldilocks:master"
          imagePullPolicy: Always
          command:
            - /goldilocks
            - web
            - --exclude-containers=linkerd-proxy,istio-proxy
            - -v3
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10324
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 25m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
